# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1b034cb9459a08c2733dde818c61d516e38f42b67ec9697d9252b129ef03bc6e723ff1b4f431496820b4e8563e253277255d47626cc3197a0d960cb7f10bea

test:
  secret_key_base: c4a0babb7018967e7b7d21ed70bb7d396db606b50ff58e7558dfaaaaa1edc3912bc60cda1c980a3d02f1b48fd8d7dd771134c4343e5a4fd44d9c001b9c25cf7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
